### ISSUE TITLE
TS Issue

### ISSUE THREAD

**Issue by zRelux** [retyui/react-native-stylex#12]
When copying the example in the README I get this error.
`Module '"react-native-stylex/media-query"' has no exported member 'createBreakpoints'.`

**Comment by retyui** [comment]
@zRelux thanks for reporting! Will fix it soon

**Comment by retyui** [comment]
Fixed in [4.1.1](https://github.com/retyui/react-native-stylex/blob/master/CHANGELOG.md#411)

Diff: [4.1.0...4.1.1](https://npmfs.com/compare/react-native-stylex/4.1.0/4.1.1/)
