### ISSUE TITLE
Dynamic Styling

### ISSUE THREAD

**Issue by hlspablo** [retyui/react-native-stylex#16]
Hi @retyui, congratulations for the library, I really loved it. 
I have a question, how I make dynamic styling in this library without having to do it conditionally on the component.
( I don't know if doing it in the component is the recommended way, but I really dont like, bloats the component a lot )
I think in something like this:
```typescript
import { makeUseStyles } from "react-native-stylex";

export const useStyles = makeUseStyles(() => ({
  container: {
    height: "60%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  // Define a function that returns a style object
  coverImage: (dynamicHeight: string, dynamicWidth: string) => ({
    height: dynamicHeight,
    width: dynamicWidth,
  }),
}));
```
where I can have a function that returns a ViewStyle, instead of only ViewStyle.

I ask if this is possible and if not, it would be possible to implement and what are the considerations?
In my tests, currently  the typescript complains about it since it expects that the object values be a ViewStyle compatible object

**Comment by retyui** [comment]
Currently, such feature is not supported.

---

further pref. optimization is needed, since 
```tsx
 coverImage: (dynamicHeight, dynamicWidth) => ({ ... }), 
//                                             ^^^^^ return new obj. on each render
```

**Comment by hlspablo** [comment]
@retyui do you think this pattern makes any sense?
i think that's a really clean way, but performance is always preferable.
If you think that makes any sense, there a possibility to implement? if not, could you give me some directions on how to implement?

**Comment by hlspablo** [comment]
closing, I found that https://github.com/jpudysz/react-native-unistyles, has this featured implemented and everything else. but thanks @retyui for you great work in this lib.

**Comment by retyui** [comment]
Also, I added list of alternative solutions
- https://github.com/retyui/react-native-stylex?tab=readme-ov-file#alternative-solutions
